#docker-compose --file docker-compose-scale.yml up -d --build --scale message-server=3 product-server=2
#docker-compose --file docker-compose-scale.yml up -d --build --scale message-server=3 product-server=2
version: '2'
services:
  message-server:
    build:
      context: docker-message-server
      dockerfile: Dockerfile
    image: message-server:latest
    ports:
      - "18000-18003:8080"
    networks:
      - spring-cloud-network
  product-server:
    build:
      context: docker-product-server
      dockerfile: Dockerfile
    image: product-server:latest
    ports:
      - "19000-19003:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge